spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile

    profiles:
    active: dev
application:
  jwt:

    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
